### ISSUE TITLE
Build issue for Release/1.12.2 in CMAKE_BUILD_TYPE=Debug mode

### ISSUE THREAD

**Issue by marcdegraef** [HDFGroup/hdf5_plugins#47]
Hi,

I am trying to build the plugins (1.12.2) and managed to do so as a standalone set of libraries for CMAKE_BUILD_TYPE=Release. 
I am building on Mac OS X 10.14.6. When I attempt to build in Debug mode, however, I run into issues with libbzz and liblzf not properly building.  The configure script is as follows: 

#!/bin/csh
setenv HDF5_ROOT "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug"
setenv PLUGIN_SOURCE "/Users/mdg/hdf5_plugins"
cmake -C ${PLUGIN_SOURCE}/config/cmake/cacheinit.cmake -DCMAKE_INSTALL_PREFIX=${HDF5_ROOT} -DHDF5_INCLUDE_DIR=${HDF5_ROOT}/include/ -DHDF5_LINK_LIBS=${HDF5_ROOT}/lib/ -DCMAKE_BUILD_TYPE:STRING=Debug -DUSE_SHARED_LIBS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DTGZPATH:PATH=${PLUGIN_SOURCE}/libs -DH5PL_ALLOW_EXTERNAL_SUPPORT:STRING=\"TGZ\" ${PLUGIN_SOURCE}

**The output when I execute this script (everything looks normal):**

loading initial cache file /Users/mdg/hdf5_plugins/config/cmake/cacheinit.cmake
-- The C compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- HDF5 find comps: C;shared
-- HDF5 C libs:1 static: and shared:1
-- HDF5 found: INC=/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include; TOOLS=/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/bin
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- HDF5 link libs: hdf5::hdf5-shared
Configuring for bshuf HDF5 Plugin version: h5bshuf 1.0
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for 5 include files sys/stat.h, ..., unistd.h
-- Looking for 5 include files sys/stat.h, ..., unistd.h - found
-- Looking for 6 include files sys/stat.h, ..., io.h
-- Looking for 6 include files sys/stat.h, ..., io.h - not found
-- Looking for 6 include files sys/stat.h, ..., winsock2.h
-- Looking for 6 include files sys/stat.h, ..., winsock2.h - not found
-- Looking for 6 include files sys/stat.h, ..., pthread.h
-- Looking for 6 include files sys/stat.h, ..., pthread.h - found
-- Looking for 7 include files sys/stat.h, ..., string.h
-- Looking for 7 include files sys/stat.h, ..., string.h - found
-- Looking for 8 include files sys/stat.h, ..., strings.h
-- Looking for 8 include files sys/stat.h, ..., strings.h - found
-- Looking for 9 include files sys/stat.h, ..., stdlib.h
-- Looking for 9 include files sys/stat.h, ..., stdlib.h - found
-- Looking for 10 include files sys/stat.h, ..., memory.h
-- Looking for 10 include files sys/stat.h, ..., memory.h - found
-- Looking for 11 include files sys/stat.h, ..., dlfcn.h
-- Looking for 11 include files sys/stat.h, ..., dlfcn.h - found
-- Looking for 12 include files sys/stat.h, ..., fcntl.h
-- Looking for 12 include files sys/stat.h, ..., fcntl.h - found
-- Looking for 13 include files sys/stat.h, ..., inttypes.h
-- Looking for 13 include files sys/stat.h, ..., inttypes.h - found
-- Looking for 14 include files sys/stat.h, ..., stdbool.h
-- Looking for 14 include files sys/stat.h, ..., stdbool.h - found
-- Looking for ceil in m;
-- Looking for ceil in m; - found
-- Looking for dlopen in dl;m
-- Looking for dlopen in dl;m - found
-- Looking for WSAStartup in ws2_32;m;dl
-- Looking for WSAStartup in ws2_32;m;dl - not found
-- Looking for gethostbyname in wsock32;m;dl
-- Looking for gethostbyname in wsock32;m;dl - not found
-- Looking for gethostname in ucb;m;dl
-- Looking for gethostname in ucb;m;dl - not found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of unsigned
-- Check size of unsigned - done
-- Check size of long long
-- Check size of long long - done
-- Check size of __int64
-- Check size of __int64 - failed
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Check size of long double
-- Check size of long double - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int_least8_t
-- Check size of int_least8_t - done
-- Check size of uint_least8_t
-- Check size of uint_least8_t - done
-- Check size of int_fast8_t
-- Check size of int_fast8_t - done
-- Check size of uint_fast8_t
-- Check size of uint_fast8_t - done
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of int_least16_t
-- Check size of int_least16_t - done
-- Check size of uint_least16_t
-- Check size of uint_least16_t - done
-- Check size of int_fast16_t
-- Check size of int_fast16_t - done
-- Check size of uint_fast16_t
-- Check size of uint_fast16_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of int_least32_t
-- Check size of int_least32_t - done
-- Check size of uint_least32_t
-- Check size of uint_least32_t - done
-- Check size of int_fast32_t
-- Check size of int_fast32_t - done
-- Check size of uint_fast32_t
-- Check size of uint_fast32_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int_least64_t
-- Check size of int_least64_t - done
-- Check size of uint_least64_t
-- Check size of uint_least64_t - done
-- Check size of int_fast64_t
-- Check size of int_fast64_t - done
-- Check size of uint_fast64_t
-- Check size of uint_fast64_t - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of off64_t
-- Check size of off64_t - failed
-- Check size of time_t
-- Check size of time_t - done
-- Check size of bool
-- Check size of bool - done
-- Looking for vprintf
-- Looking for vprintf - found
-- Looking for _doprnt
-- Looking for _doprnt - not found
-- Looking for memset
-- Looking for memset - found
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5BSHUF link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Configuring for blosc HDF5 Plugin version: h5blosc 1.0.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5BLOSC link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- BLOSC is built
-- BLOSC is ON
Configuring for bz2 HDF5 Plugin version: h5bz2 1.0.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5BZ2 link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Filter BZ2 is built
-- bz2 found: INC=/Users/mdg/hdf5_plugins_build/BZIP2/BZ2-prefix/src/BZ2/src LIBS=bz2
Configuring for jpeg HDF5 Plugin version: h5jpeg 1.0.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5JPEG link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Filter JPEG is built
-- jpeg found: INC=/Users/mdg/hdf5_plugins_build/JPEG/JPEG-prefix/src/JPEG/src LIBS=jpeg
Configuring for lz4 HDF5 Plugin version: h5lz4 1.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5LZ4 link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
Configuring for lzf HDF5 Plugin version: h5lzf 1.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5LZF link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Filter LZF is built
-- lzf found: INC=/Users/mdg/hdf5_plugins_build/LZF/LZF-prefix/src/LZF TOOLS=lzf
Configuring for SZ HDF5 Plugin version: h5sz 1.0
-- Looking for include file sys/file.h
-- Looking for include file sys/file.h - found
-- Looking for include files sys/file.h, sys/ioctl.h
-- Looking for include files sys/file.h, sys/ioctl.h - found
-- Looking for 3 include files sys/file.h, ..., sys/resource.h
-- Looking for 3 include files sys/file.h, ..., sys/resource.h - found
-- Looking for 4 include files sys/file.h, ..., sys/socket.h
-- Looking for 4 include files sys/file.h, ..., sys/socket.h - found
-- Looking for 6 include files sys/file.h, ..., sys/time.h
-- Looking for 6 include files sys/file.h, ..., sys/time.h - found
-- Looking for 8 include files sys/file.h, ..., features.h
-- Looking for 8 include files sys/file.h, ..., features.h - not found
-- Looking for 8 include files sys/file.h, ..., dirent.h
-- Looking for 8 include files sys/file.h, ..., dirent.h - found
-- Looking for 12 include files sys/file.h, ..., mach/mach_time.h
-- Looking for 12 include files sys/file.h, ..., mach/mach_time.h - found
-- Looking for 13 include files sys/file.h, ..., sys/timeb.h
-- Looking for 13 include files sys/file.h, ..., sys/timeb.h - found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - not found
-- Performing Test HAVE_TIMESPEC
-- Performing Test HAVE_TIMESPEC - Success
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Performing Test HAVE___TM_GMTOFF
-- Performing Test HAVE___TM_GMTOFF - Failed
-- Performing Test TIME_WITH_SYS_TIME
-- Performing Test TIME_WITH_SYS_TIME - Success
-- Performing Test HAVE_STRUCT_TIMEZONE
-- Performing Test HAVE_STRUCT_TIMEZONE - Failed
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5SZ link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Filter SZ is built
-- SZ found: INC=/Users/mdg/hdf5_plugins_build/SZ/SZF-prefix/src/SZF/sz/include TOOLS=SZ;zstd;ZLIB
Configuring for zfp HDF5 Plugin version: h5zfp 1.0
-- HDF5 link libs: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared Includes: /Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/include
-- H5ZFP link libs: m;dl;/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/;hdf5::hdf5-shared
-- Filter ZFP is built
-- zfp found: INC=/Users/mdg/hdf5_plugins_build/ZFP/ZFP-prefix/src/ZFP/include TOOLS=zfp
-- Configuring done
WARNING: Target "h5bshuf" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_bshuf" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5blosc" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_blosc" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5bz2" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_bzip2" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5jpeg" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_jpeg" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5lz4" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_lz4" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5lzf" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_lzf" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5sz" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_sz" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5zfp" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "h5ex_d_zfp" requests linking to directory "/Users/Shared/EMsoftOO_SDK/hdf5-1.12.2-Debug/lib/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /Users/mdg/hdf5_plugins_build

**When I compile using "make" the process stops with the following error:**

..... many lines deleted
[ 32%] Performing build step for 'BZ2'
Scanning dependencies of target bz2-static
[ 12%] Building C object src/CMakeFiles/bz2-static.dir/blocksort.c.o
[ 25%] Building C object src/CMakeFiles/bz2-static.dir/huffman.c.o
[ 37%] Building C object src/CMakeFiles/bz2-static.dir/crctable.c.o
[ 50%] Building C object src/CMakeFiles/bz2-static.dir/randtable.c.o
[ 62%] Building C object src/CMakeFiles/bz2-static.dir/compress.c.o
[ 75%] Building C object src/CMakeFiles/bz2-static.dir/decompress.c.o
[ 87%] Building C object src/CMakeFiles/bz2-static.dir/bzlib.c.o
[100%] Linking C static library /Users/mdg/hdf5_plugins_build/bin/libbz2_debug.a
[100%] Built target bz2-static
[ 33%] No install step for 'BZ2'
[ 33%] Completed 'BZ2'
[ 33%] Built target BZ2
Scanning dependencies of target h5bz2
[ 34%] Building C object BZIP2/src/CMakeFiles/h5bz2.dir/H5Zbzip2.c.o
make[2]: *** No rule to make target `bin/libbz2.a', needed by `bin/libh5bz2.so'.  Stop.
make[1]: *** [BZIP2/src/CMakeFiles/h5bz2.dir/all] Error 2
make: *** [all] Error 2

This works fine in Release mode, so maybe there is a problem in one of the CMake files ?

Thanks!
Marc.

**Comment by byrnHDF** [comment]
It might be expecting a debug hdf5?

**Comment by byrnHDF** [comment]
CMake build code has been reworked, and building debug has passed with hdf5_plugins master and hdf5 develop .

**Comment by derobins** [comment]
Can this be closed?

**Comment by byrnHDF** [comment]
Close this as testing does not indicate any errors
