### ISSUE TITLE
TRPX integration

### ISSUE THREAD

**Issue by senikm** [HDFGroup/hdf5_plugins#99]
Dear developers,

We would like to draw your attention to the TRPX algorithm we have developed. The package has been open-sourced under the MIT license and is available on GitHub at [this link](https://github.com/Senikm/trpx). Additionally, you can find the associated paper here: https://journals.iucr.org/a/issues/2023/06/00/lu5031/index.html. We would be happy to see it included as a plugin in hdf5_plugins.

All the best,
Senik

**Comment by bmribler** [comment]
Hello @senikm, you can see how to register a filter [here](https://github.com/HDFGroup/hdf5_plugins/blob/master/docs/RegisteredFilterPlugins.md).

We currently don't have a process for including the filter as a plugin in hdf5_plugins yet.  Users would use the filters as provided by the authors.  Please see the registered filters for example on information that you want to provide.
Thanks!
